# Generated by Django 5.1.4 on 2025-02-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_reset_hash',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pass_reset_hash_status',
            field=models.BooleanField(default=False),
        ),
    ]
